"""imageіs5

Revision ID: 0fdb7aa8044a
Revises: 63c1abcc9413
Create Date: 2023-04-08 19:50:49.865812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdb7aa8044a'
down_revision = '63c1abcc9413'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
