"""Teble User update email_verified

Revision ID: 0fe8d246ce21
Revises: d70d25a61332
Create Date: 2023-03-29 19:13:51.145452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe8d246ce21'
down_revision = 'd70d25a61332'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
