"""Table User add updated_at

Revision ID: 121f6007e492
Revises: 0fe8d246ce21
Create Date: 2023-03-29 19:23:28.623932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121f6007e492'
down_revision = '0fe8d246ce21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
