"""imageіs4

Revision ID: 63c1abcc9413
Revises: 78414e6f264c
Create Date: 2023-04-08 19:44:59.895135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63c1abcc9413'
down_revision = '78414e6f264c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
