"""imageіs3

Revision ID: 78414e6f264c
Revises: 859f79bd5f9e
Create Date: 2023-04-08 19:35:31.273879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78414e6f264c'
down_revision = '859f79bd5f9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
