"""comments

Revision ID: 794dbbec0028
Revises: c21dee053e7f
Create Date: 2023-04-08 22:25:18.921136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '794dbbec0028'
down_revision = 'c21dee053e7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
