"""imageі2

Revision ID: 859f79bd5f9e
Revises: c21dee053e7f
Create Date: 2023-04-08 19:31:35.655157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859f79bd5f9e'
down_revision = 'c21dee053e7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_ratings')
    op.drop_column('images', 'average_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False))
    op.create_table('image_ratings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name='image_ratings_image_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='image_ratings_user_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='image_ratings_pkey'),
    sa.UniqueConstraint('user_id', 'image_id', name='unique_user_image_rating')
    )
    # ### end Alembic commands ###
