"""images6

Revision ID: d7d4d3fba71d
Revises: f0d769abcad5
Create Date: 2023-04-08 20:07:14.852752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d4d3fba71d'
down_revision = 'f0d769abcad5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
