"""images5

Revision ID: f0d769abcad5
Revises: 0fdb7aa8044a
Create Date: 2023-04-08 20:00:12.653420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d769abcad5'
down_revision = '0fdb7aa8044a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
